=== Krishna-Karki/Web_development_learning/XML/4.schemavalid.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Cars">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="car">

                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="speed" type="xs:float"></xs:element>
                            <xs:element name="price" type="xs:integer"></xs:element>

                        </xs:sequence>
                    </xs:complexType>

                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Krishna-Karki/Web_development_learning/XML/4.schemavalidation.xml
<?xml version="1.0" encoding="UTF-8"?>

<Cars xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="4.schemavalid.xsd"
> 
    <car>
        <name>Audi</name>
        <speed>300</speed>
        <price>200000</price>
    </car>

    <car>
        <name>Mercedes</name>
        <speed>200</speed>
        <price>100000</price>
    </car>

</Cars>
